// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI Supplement Advisor flow.
 *
 * This file defines a Genkit flow that suggests supplements based on user input
 * of fitness goals, dietary restrictions, and workout routines.
 *
 * @exports supplementAdvisor - The main function to call the flow.
 * @exports SupplementAdvisorInput - The input type for the supplementAdvisor function.
 * @exports SupplementAdvisorOutput - The return type for the supplementAdvisor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SupplementAdvisorInputSchema = z.object({
  fitnessGoals: z
    .string()
    .describe('The fitness goals of the user (e.g., build muscle, lose weight, increase endurance).'),
  dietaryRestrictions: z
    .string()
    .describe('Any dietary restrictions the user has (e.g., vegetarian, vegan, gluten-free).'),
  workoutRoutine: z
    .string()
    .describe('The typical workout routine of the user (e.g., cardio, weightlifting, crossfit).'),
});

export type SupplementAdvisorInput = z.infer<typeof SupplementAdvisorInputSchema>;

const SupplementAdvisorOutputSchema = z.object({
  suggestedSupplements: z
    .string()
    .describe('A list of suggested supplements based on the user input.'),
  reasoning: z.string().describe('The reasoning behind the supplement suggestions.'),
});

export type SupplementAdvisorOutput = z.infer<typeof SupplementAdvisorOutputSchema>;

export async function supplementAdvisor(input: SupplementAdvisorInput): Promise<SupplementAdvisorOutput> {
  return supplementAdvisorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'supplementAdvisorPrompt',
  input: {schema: SupplementAdvisorInputSchema},
  output: {schema: SupplementAdvisorOutputSchema},
  prompt: `You are a knowledgeable supplement advisor. Based on the user's fitness goals, dietary restrictions, and workout routine, you will suggest suitable supplements.

Fitness Goals: {{{fitnessGoals}}}
Dietary Restrictions: {{{dietaryRestrictions}}}
Workout Routine: {{{workoutRoutine}}}

Provide a list of suggested supplements and a brief explanation of why each supplement is recommended.
`,
});

const supplementAdvisorFlow = ai.defineFlow(
  {
    name: 'supplementAdvisorFlow',
    inputSchema: SupplementAdvisorInputSchema,
    outputSchema: SupplementAdvisorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
